Repository DMTF/libspdm, pull requests merged in 2022-11, with the labels that each got.

#1332 Enable code coverage generation in CI/CD
  .github/workflows/code_coverage.yml
Labels: enhancement, test

#1342 Work around build failure when GCOV is on
  .github/workflows/code_coverage.yml
Labels: test

#1350 Add test_crypt and test_spdm_crypt return for CI
  unit_test/test_crypt/test_crypt.c
  unit_test/test_spdm_crypt/test_spdm_crypt.c
Labels: test

#1375 Expand GET_CAPABILITIES unit test coverage
  library/spdm_requester_lib/libspdm_req_get_capabilities.c
  unit_test/test_spdm_requester/error_test/get_capabilities_err.c
Labels: test

#1378 Enable manual trigger for build
  .github/workflows/build.yml
Labels: test

#1386 Run CodeQL daily
  .github/workflows/codeql-analysis.yml
Labels: test

#1390 Expand NEGOTIATE_ALGORITHMS code coverage
  unit_test/test_spdm_requester/error_test/negotiate_algorithms_err.c
Labels: test

#1421 Improve fuzzy test coverage
  unit_test/fuzzing/test_requester/test_spdm_requester_heartbeat/heartbeat.c
  unit_test/fuzzing/test_responder/test_spdm_responder_heartbeat_ack/heartbeat_ack.c
Labels: enhancement, test

#1427 Rename test names in CI / CD
  .github/workflows/build.yml
Labels: test, refactor

#1432 Delete Doxygen comments from spdm_requester_lib implementations
  library/spdm_requester_lib/libspdm_req_communication.c
  library/spdm_requester_lib/libspdm_req_encap_certificate.c
  library/spdm_requester_lib/libspdm_req_encap_challenge_auth.c
  library/spdm_requester_lib/libspdm_req_encap_digests.c
  library/spdm_requester_lib/libspdm_req_encap_error.c
  library/spdm_requester_lib/libspdm_req_encap_key_update.c
  library/spdm_requester_lib/libspdm_req_encap_request.c
  library/spdm_requester_lib/libspdm_req_finish.c
  library/spdm_requester_lib/libspdm_req_get_capabilities.c
  library/spdm_requester_lib/libspdm_req_get_certificate.c
  library/spdm_requester_lib/libspdm_req_get_csr.c
  library/spdm_requester_lib/libspdm_req_get_version.c
  library/spdm_requester_lib/libspdm_req_handle_error_response.c
  library/spdm_requester_lib/libspdm_req_key_exchange.c
  library/spdm_requester_lib/libspdm_req_key_update.c
  library/spdm_requester_lib/libspdm_req_psk_exchange.c
  library/spdm_requester_lib/libspdm_req_send_receive.c
  library/spdm_requester_lib/libspdm_req_set_certificate.c
Labels: refactor

#1433 Delete Doxygen comments from spdm_responder_lib implementations
  library/spdm_responder_lib/libspdm_rsp_algorithms.c
  library/spdm_responder_lib/libspdm_rsp_capabilities.c
  library/spdm_responder_lib/libspdm_rsp_certificate.c
  library/spdm_responder_lib/libspdm_rsp_challenge_auth.c
  library/spdm_responder_lib/libspdm_rsp_chunk_get.c
  library/spdm_responder_lib/libspdm_rsp_chunk_send_ack.c
  library/spdm_responder_lib/libspdm_rsp_communication.c
  library/spdm_responder_lib/libspdm_rsp_csr.c
  library/spdm_responder_lib/libspdm_rsp_digests.c
  library/spdm_responder_lib/libspdm_rsp_encap_challenge.c
  library/spdm_responder_lib/libspdm_rsp_encap_get_certificate.c
  library/spdm_responder_lib/libspdm_rsp_encap_get_digests.c
  library/spdm_responder_lib/libspdm_rsp_encap_response.c
  library/spdm_responder_lib/libspdm_rsp_end_session.c
  library/spdm_responder_lib/libspdm_rsp_error.c
  library/spdm_responder_lib/libspdm_rsp_finish.c
  library/spdm_responder_lib/libspdm_rsp_handle_response_state.c
  library/spdm_responder_lib/libspdm_rsp_heartbeat.c
  library/spdm_responder_lib/libspdm_rsp_key_exchange.c
  library/spdm_responder_lib/libspdm_rsp_measurements.c
  library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
  library/spdm_responder_lib/libspdm_rsp_psk_finish.c
  library/spdm_responder_lib/libspdm_rsp_respond_if_ready.c
  library/spdm_responder_lib/libspdm_rsp_set_certificate.c
  library/spdm_responder_lib/libspdm_rsp_version.c
Labels: refactor

#1431 Delete Doxygen comments from spdm_crypt_lib implementations
  include/library/spdm_crypt_lib.h
  library/spdm_crypt_lib/libspdm_crypt_aead.c
  library/spdm_crypt_lib/libspdm_crypt_asym.c
  library/spdm_crypt_lib/libspdm_crypt_cert.c
  library/spdm_crypt_lib/libspdm_crypt_dhe.c
  library/spdm_crypt_lib/libspdm_crypt_hash.c
  library/spdm_crypt_lib/libspdm_crypt_hkdf.c
  library/spdm_crypt_lib/libspdm_crypt_hmac.c
  library/spdm_crypt_lib/libspdm_crypt_rng.c
  os_stub/spdm_crypt_ext_lib/spdm_crypt_ext.c
  os_stub/spdm_crypt_ext_lib/spdm_crypt_ext_lib.h
Labels: refactor
