Repository DMTF/libspdm, pull requests merged in 2022-10, with the labels that each got.

#1251 Update VERSION.md to 2.2.0 and released
  VERSION.md
Labels: documentation

#1254 Update VERSION.md after the 2.2.0 release
  VERSION.md
Labels: documentation

#1255 Omit CodeQL if only documents are updated
  .github/workflows/codeql-analysis.yml
Labels: test

#1257 Split libspdm_crypt_crypt into separate files
  include/internal/libspdm_crypt_lib.h
  library/spdm_crypt_lib/CMakeLists.txt
  library/spdm_crypt_lib/libspdm_crypt_aead.c
  library/spdm_crypt_lib/libspdm_crypt_asym.c
  library/spdm_crypt_lib/libspdm_crypt_cert.c
  library/spdm_crypt_lib/libspdm_crypt_crypt.c
  library/spdm_crypt_lib/libspdm_crypt_dhe.c
  library/spdm_crypt_lib/libspdm_crypt_hash.c
  library/spdm_crypt_lib/libspdm_crypt_hkdf.c
  library/spdm_crypt_lib/libspdm_crypt_hmac.c
  library/spdm_crypt_lib/libspdm_crypt_rng.c
Labels: refactor

#1287 Refactor Responder VCA
  library/spdm_responder_lib/libspdm_rsp_algorithms.c
  library/spdm_responder_lib/libspdm_rsp_capabilities.c
  library/spdm_responder_lib/libspdm_rsp_version.c
Labels: refactor

#1293 Clean up integrator-visible headers
  include/library/spdm_common_lib.h
  include/library/spdm_requester_lib.h
Labels: refactor

#1294 Move functions from public common_lib to internal
  include/internal/libspdm_common_lib.h
  include/library/spdm_common_lib.h
Labels: refactor

#1309 Update the unit tests of spdm_responder_version.
  unit_test/test_spdm_responder/version.c
Labels: test

#1322 Move the LIBSPDM_CONFIG logic
  include/hal/library/cryptlib.h
  include/internal/libspdm_lib_config.h
  include/library/spdm_common_lib.h
  include/library/spdm_crypt_lib.h
  include/library/spdm_device_secret_lib.h
Labels: enhancement, refactor
