Repository DMTF/libspdm, pull requests merged in 2022-12, with the labels that each got.

#1458 Rename LIBSPDM_INTERNAL_DUMP_HEX_str
  include/internal/libspdm_common_lib.h
  library/spdm_common_lib/libspdm_com_support.c
Labels: refactor

#1482 Change http:// to https:// where appropriate
  doc/test.md
  library/spdm_crypt_lib/libspdm_crypt_cert.c
Labels: enhancement, security

#1492 Fixing potentially uninitialized warning in KEY_UPDATE callbacks.
  library/spdm_requester_lib/libspdm_req_send_receive.c
  library/spdm_responder_lib/libspdm_rsp_receive_send.c
Labels: bug

#1493 Add capability macros to spdm_device_secret_lib
  .github/workflows/build.yml
  include/library/spdm_device_secret_lib.h
Labels: enhancement

#1483 Add AlgType checker
  library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c
  library/spdm_responder_lib/libspdm_rsp_algorithms.c
  unit_test/test_spdm_requester/error_test/negotiate_algorithms_err.c
  unit_test/test_spdm_responder/algorithms.c
  unit_test/test_spdm_responder/chunk_send_ack.c
Labels: enhancement

#1531 Make test_crypt pass with less crypt enabled.
  unit_test/test_crypt/test_crypt.h
Labels: test

#1540 remove LIBSPDM_MAX_MEASUREMENT_BLOCK_COUNT.
  include/library/spdm_lib_config.h
  library/spdm_requester_lib/libspdm_req_get_measurements.c
  library/spdm_responder_lib/libspdm_rsp_measurements.c
  os_stub/spdm_device_secret_lib_sample/lib.c
Labels: enhancement

#1544 Add macro checks to cryptlib
  include/hal/library/cryptlib/cryptlib_dh.h
  include/hal/library/cryptlib/cryptlib_ec.h
  include/hal/library/cryptlib/cryptlib_ecd.h
  include/hal/library/cryptlib/cryptlib_sm2.h
  os_stub/spdm_crypt_ext_lib/cryptlib_ext.h
  os_stub/spdm_device_secret_lib_sample/spdm_device_secret_lib_internal.h
  unit_test/test_crypt/ec_verify.c
  unit_test/test_crypt/sm2_verify.c
  unit_test/test_crypt/test_crypt.c
Labels: enhancement

#1552 fix test case issue on measurement_hash
  unit_test/spdm_unit_test_common/algo.c
  unit_test/test_spdm_requester/error_test/key_exchange_err.c
  unit_test/test_spdm_requester/key_exchange.c
  unit_test/test_spdm_requester/psk_exchange.c
Labels: test
