Repository DMTF/libspdm, pull requests merged in 2023-10, with the labels that each got.

#2378 Remove 1.2.1 capability checks from Requester
  library/spdm_requester_lib/libspdm_req_get_csr.c
  library/spdm_requester_lib/libspdm_req_handle_error_response.c
  library/spdm_requester_lib/libspdm_req_set_certificate.c
Labels: bug

#2384 Add API documentation for endianness
  doc/api/common_api.md
  include/library/spdm_common_lib.h
  library/spdm_common_lib/libspdm_com_context_data.c
Labels: documentation

#2389 Fix up documentation before 3.1 release
  README.md
  doc/aead_limit.md
  doc/crypto_endianness.md
  doc/raw_public_key.md
Labels: documentation

#2396 Skip AEAD endianness detection
  library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c
  unit_test/test_spdm_secured_message/encode_decode.c
Labels: bug

#2407 fix measurement summary hash calculation.
  os_stub/spdm_device_secret_lib_sample/lib.c
Labels: bug

#2409 Add more unit tests for SPDM secured messages
  unit_test/test_spdm_secured_message/encode_decode.c
Labels: test

#2416 Add version check code for some fields in GET_CAPABILITIES and CAPABLITIES messages
  library/spdm_requester_lib/libspdm_req_get_capabilities.c
  library/spdm_responder_lib/libspdm_rsp_capabilities.c
Labels: enhancement
