Repository DMTF/libspdm, pull requests merged in 2023-06, with the labels that each got.

#2095 Fix logic error when use libspdm_consttime_is_mem_equal
  unit_test/test_spdm_responder/csr.c
Labels: bug

#2098 Fix sm2 end_cert generate
  unit_test/sample_key/readme.txt
  unit_test/sample_key/sm2/bundle_requester.certchain.der
  unit_test/sample_key/sm2/bundle_responder.certchain.der
  unit_test/sample_key/sm2/end_requester.cert
  unit_test/sample_key/sm2/end_requester.cert.der
  unit_test/sample_key/sm2/end_responder.cert
  unit_test/sample_key/sm2/end_responder.cert.der
Labels: bug

#2113 Move Responder's certificate chain buffer
  include/internal/libspdm_common_lib.h
  library/spdm_common_lib/libspdm_com_context_data.c
  library/spdm_responder_lib/libspdm_rsp_encap_get_certificate.c
  library/spdm_responder_lib/libspdm_rsp_encap_response.c
  library/spdm_responder_lib/libspdm_rsp_receive_send.c
  unit_test/fuzzing/test_responder/test_spdm_responder_encap_get_certificate/encap_get_certificate.c
  unit_test/test_spdm_responder/encap_get_certificate.c
Labels: bug

#2111 Fix incorrect variable names for unit tests
  unit_test/test_spdm_responder/challenge_auth.c
Labels: test

#2117 `return false;` in `libspdm_rsp_measurements.c` should be changed to `return libspdm_generate_error_response`
  library/spdm_responder_lib/libspdm_rsp_measurements.c
Labels: bug

#2116 fix wrong request variable name
  unit_test/test_spdm_responder/challenge_auth.c
Labels: test

#2127 Update unit test to check Completion of CHALLENGE sets M1/M2 to null.
  unit_test/test_spdm_requester/challenge.c
  unit_test/test_spdm_requester/encap_challenge_auth.c
  unit_test/test_spdm_responder/challenge_auth.c
  unit_test/test_spdm_responder/encap_challenge.c
Labels: test

#2130 Add LIBSPDM_MAX_SPDM_SESSION_SEQUENCE_NUMBER
  include/internal/libspdm_common_lib.h
  include/internal/libspdm_secured_message_lib.h
  include/library/spdm_common_lib.h
  library/spdm_common_lib/libspdm_com_context_data.c
  library/spdm_common_lib/libspdm_com_context_data_session.c
  library/spdm_secured_message_lib/libspdm_secmes_context_data.c
  library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c
Labels: enhancement

#2120 CMakeLists: Allow disabling tests
  .github/workflows/build.yml
  CMakeLists.txt
  doc/build.md
Labels: test

#2110 Fix `libspdm_test_responder_measurements_case22` version mismatch
  unit_test/test_spdm_responder/measurements.c
Labels: test

#2136 start watchdog in case of PSK without context.
  library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
Labels: bug

#2122 Auto generate raw data key
  os_stub/spdm_device_secret_lib_sample/lib.c
  os_stub/spdm_device_secret_lib_sample/raw_data_key.h
  unit_test/sample_key/raw_data_key_gen.py
  unit_test/sample_key/readme.txt
Labels: enhancement

#2140 Fix encapsulated GET_CERTIFICATE bug
  library/spdm_responder_lib/libspdm_rsp_encap_get_certificate.c
Labels: bug

#2168 fix typo in libspdm_get_hash_size
  library/spdm_crypt_lib/libspdm_crypt_hash.c
Labels: bug

#2170 Add line break
  library/spdm_common_lib/libspdm_com_context_data.c
Labels: enhancement

#2134 reorg the secretlib.
  include/hal/library/requester/psklib.h
  include/hal/library/requester/reqasymsignlib.h
  include/hal/library/requester/timelib.h
  include/hal/library/responder/asymsignlib.h
  include/hal/library/responder/csrlib.h
  include/hal/library/responder/measlib.h
  include/hal/library/responder/psklib.h
  include/hal/library/responder/setcertlib.h
  include/hal/library/responder/watchdoglib.h
  include/hal/library/responder_secretlib.h
  include/internal/libspdm_common_lib.h
  include/internal/libspdm_requester_lib.h
  include/internal/libspdm_responder_lib.h
  library/spdm_requester_lib/libspdm_req_encap_challenge_auth.c
  os_stub/spdm_device_secret_lib_null/lib.c
  os_stub/spdm_device_secret_lib_sample/lib.c
  os_stub/spdm_device_secret_lib_sample/spdm_device_secret_lib_internal.h
Labels: enhancement

#2182 memlib enhancements
  include/hal/library/debuglib.h
  include/hal/library/memlib.h
  os_stub/memlib/copy_mem.c
  os_stub/memlib/set_mem.c
  os_stub/memlib/zero_mem.c
Labels: enhancement

#2183 Delete extra cached CSR
  os_stub/spdm_device_secret_lib_sample/lib.c
  unit_test/sample_key/test_csr/Readme.txt
  unit_test/sample_key/test_csr/cached.csr
  unit_test/sample_key/test_csr/ecc256.key
  unit_test/sample_key/test_csr/ecc384.key
  unit_test/sample_key/test_csr/ecc521.key
  unit_test/sample_key/test_csr/ecp256.csr
  unit_test/sample_key/test_csr/ecp384.csr
  unit_test/sample_key/test_csr/ecp521.csr
  unit_test/sample_key/test_csr/param.pem
  unit_test/sample_key/test_csr/rsa2048.csr
  unit_test/sample_key/test_csr/rsa2048.key
  unit_test/sample_key/test_csr/rsa3072.csr
  unit_test/sample_key/test_csr/rsa3072.key
  unit_test/sample_key/test_csr/rsa4096.csr
  unit_test/sample_key/test_csr/rsa4096.key
  unit_test/test_spdm_requester/get_csr.c
  unit_test/test_spdm_responder/csr.c
Labels: test

#2144 Add unit_test for set_cert to check overwrite same slot_id
  os_stub/spdm_device_secret_lib_sample/lib.c
  unit_test/spdm_unit_test_common/support.c
  unit_test/test_spdm_responder/set_certificate_rsp.c
Labels: test

#2180 Add unit test for LargeResponse shall not be allowed in ResponseToLar…
  unit_test/test_spdm_requester/chunk_send.c
Labels: test
