Repository DMTF/libspdm, pull requests merged in 2023-03, with the labels that each got.

#1748 Prevent extra sleep in busy-retry process
  library/spdm_requester_lib/libspdm_req_challenge.c
  library/spdm_requester_lib/libspdm_req_end_session.c
  library/spdm_requester_lib/libspdm_req_finish.c
  library/spdm_requester_lib/libspdm_req_get_capabilities.c
  library/spdm_requester_lib/libspdm_req_get_certificate.c
  library/spdm_requester_lib/libspdm_req_get_csr.c
  library/spdm_requester_lib/libspdm_req_get_digests.c
  library/spdm_requester_lib/libspdm_req_get_measurements.c
  library/spdm_requester_lib/libspdm_req_get_version.c
  library/spdm_requester_lib/libspdm_req_heartbeat.c
  library/spdm_requester_lib/libspdm_req_key_exchange.c
  library/spdm_requester_lib/libspdm_req_key_update.c
  library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c
  library/spdm_requester_lib/libspdm_req_psk_exchange.c
  library/spdm_requester_lib/libspdm_req_psk_finish.c
  library/spdm_requester_lib/libspdm_req_set_certificate.c
Labels: bug

#1749 Fix incorrect error data of error code VersionMismatch.
  library/spdm_requester_lib/libspdm_req_encap_certificate.c
  library/spdm_requester_lib/libspdm_req_encap_challenge_auth.c
  library/spdm_requester_lib/libspdm_req_encap_digests.c
  library/spdm_requester_lib/libspdm_req_encap_key_update.c
Labels: bug

#1752 Fix LIBFUZZER warning
  unit_test/fuzzing/spdm_unit_fuzzing_common/toolchain_harness.c
Labels: enhancement

#1756 Fix incorrect error code if GET_ENCAPSULATED_REQUEST message is encap…
  library/spdm_requester_lib/libspdm_req_encap_request.c
Labels: bug

#1766 Move ec_get_public_key_from_der into appropriate config
  include/hal/library/cryptlib/cryptlib_ec.h
Labels: enhancement

#1779 FINISH.Param2 only valid if FINISH.Param1 == 0x01.
  library/spdm_responder_lib/libspdm_rsp_finish.c
Labels: bug

#1767 Add unit test for Invalid SlotID in FINISH request message.
  unit_test/test_spdm_responder/finish.c
Labels: test

#1783 Replace CMake `VERSION_GREATER_EQUAL` with `VERSION_GREATER `
  CMakeLists.txt
Labels: bug

#1790 Fix typo randum -> random
  include/library/spdm_secured_message_lib.h
  include/library/spdm_transport_mctp_lib.h
  library/spdm_transport_mctp_lib/libspdm_mctp_mctp.c
  library/spdm_transport_pcidoe_lib/libspdm_doe_pcidoe.c
  unit_test/include/library/spdm_transport_test_lib.h
  unit_test/spdm_transport_test_lib/test.c
Labels: refactor

#1800 Fix uncrustify warnings
  .uncrustify.cfg
Labels: bug, test

#1765 Allow the project override mbedtls config.h to reduce size.
  os_stub/mbedtlslib/CMakeLists.txt
Labels: enhancement

#1801 Add additional check to `MEASUREMENTS` validation
  library/spdm_requester_lib/libspdm_req_get_measurements.c
Labels: enhancement

#1788 spdm_responder_lib: add code name to response dump
  include/internal/libspdm_common_lib.h
  library/spdm_common_lib/libspdm_com_support.c
  library/spdm_requester_lib/libspdm_req_send_receive.c
  library/spdm_responder_lib/libspdm_rsp_receive_send.c
Labels: enhancement

#1821 Initial draft for Responder API document
  doc/api/responder_api.md
Labels: documentation

#1827 Specify architecture size
  doc/programming_environment.md
Labels: documentation

#1815 Responder shall terminate the encapsulated request flow when Requeste…
  library/spdm_responder_lib/libspdm_rsp_encap_response.c
Labels: bug

#1819 Check integer overflow.
  library/spdm_requester_lib/libspdm_req_get_certificate.c
  library/spdm_responder_lib/libspdm_rsp_encap_get_certificate.c
Labels: bug

#1828 Move secured message functions
  include/internal/libspdm_secured_message_lib.h
  include/library/spdm_responder_lib.h
  include/library/spdm_secured_message_lib.h
  library/spdm_common_lib/libspdm_com_context_data_session.c
  library/spdm_common_lib/libspdm_com_crypto_service_session.c
  library/spdm_requester_lib/libspdm_req_encap_key_update.c
  library/spdm_requester_lib/libspdm_req_end_session.c
  library/spdm_requester_lib/libspdm_req_finish.c
  library/spdm_requester_lib/libspdm_req_key_exchange.c
  library/spdm_requester_lib/libspdm_req_key_update.c
  library/spdm_requester_lib/libspdm_req_psk_exchange.c
  library/spdm_requester_lib/libspdm_req_psk_finish.c
  library/spdm_requester_lib/libspdm_req_send_receive.c
  library/spdm_responder_lib/libspdm_rsp_encap_key_update.c
  library/spdm_responder_lib/libspdm_rsp_finish.c
  library/spdm_responder_lib/libspdm_rsp_key_exchange.c
  library/spdm_responder_lib/libspdm_rsp_key_update.c
  library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
  library/spdm_responder_lib/libspdm_rsp_psk_finish.c
  library/spdm_responder_lib/libspdm_rsp_receive_send.c
  unit_test/spdm_unit_test_common/spdm_unit_test.h
Labels: enhancement

#1820 fix test_spdm_requester_encap_request related issues
  unit_test/fuzzing/seeds/test_spdm_requester_encap_request/encap_request.raw
  unit_test/fuzzing/seeds/test_spdm_requester_encap_request/encap_request11.raw
  unit_test/fuzzing/test_requester/test_spdm_requester_encap_request/encap_request.c
Labels: test

#1834 Fix typo
  include/library/spdm_secured_message_lib.h
Labels: refactor

#1844 libspdm_rsp_psk_exchange: Fixup PSK Hint Length comparison
  library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
Labels: bug

#1850 Fix the issue of unsuccessful first execution of fuzzy test
  unit_test/fuzzing/seeds/test_spdm_requester_encap_certificate/encap_certificate.raw
  unit_test/fuzzing/seeds/test_spdm_requester_encap_key_update/encap_key_update.raw
  unit_test/fuzzing/seeds/test_spdm_requester_finish/finish11.raw
  unit_test/fuzzing/seeds/test_spdm_requester_finish/finish12.raw
  unit_test/fuzzing/test_requester/test_spdm_requester_encap_certificate/encap_certificate.c
  unit_test/fuzzing/test_requester/test_spdm_requester_encap_digests/encap_digests.c
  unit_test/fuzzing/test_requester/test_spdm_requester_encap_key_update/encap_key_update.c
  unit_test/fuzzing/test_requester/test_spdm_requester_finish/finish.c
  unit_test/fuzzing/test_requester/test_spdm_requester_get_certificate/get_certificate.c
  unit_test/fuzzing/test_requester/test_spdm_requester_key_update/key_update.c
  unit_test/fuzzing/test_responder/test_spdm_responder_digests/digests.c
  unit_test/fuzzing/test_responder/test_spdm_responder_encap_get_digests/encap_get_digests.c
Labels: test

#1852 Split `libspdm_send_receive_data` into separate functions
  include/internal/libspdm_requester_lib.h
  include/library/spdm_requester_lib.h
  library/spdm_requester_lib/libspdm_req_communication.c
Labels: enhancement
