Repository DMTF/libspdm, pull requests merged in 2023-02, with the labels that each got.

#1689 Fix typo in build file
  CMakeLists.txt
Labels: refactor

#1691 Enable gcov's all_blocks for code coverage
  .github/workflows/code_coverage.yml
Labels: enhancement, test

#1685 Allow override default dump functions
  include/internal/libspdm_common_lib.h
Labels: enhancement

#1684 Remove return value from opaque build function
  include/internal/libspdm_requester_lib.h
  include/internal/libspdm_responder_lib.h
  library/spdm_requester_lib/libspdm_req_common.c
  library/spdm_requester_lib/libspdm_req_key_exchange.c
  library/spdm_requester_lib/libspdm_req_psk_exchange.c
  library/spdm_responder_lib/libspdm_rsp_common.c
  library/spdm_responder_lib/libspdm_rsp_key_exchange.c
  library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
Labels: refactor

#1686 Add unit test for MaxSPDMmsgSize less than DataTransferSize.
  unit_test/test_spdm_requester/error_test/get_capabilities_err.c
  unit_test/test_spdm_responder/capabilities.c
Labels: test

#1692 set LIB_INSTALL_DIR to build mbedtls with cmake
  os_stub/mbedtlslib/CMakeLists.txt
Labels: bug

#1693 Fix potential alignment and byte-order issue
  library/spdm_common_lib/libspdm_com_context_data.c
  library/spdm_requester_lib/libspdm_req_challenge.c
  library/spdm_requester_lib/libspdm_req_get_measurements.c
  library/spdm_requester_lib/libspdm_req_key_exchange.c
  library/spdm_responder_lib/libspdm_rsp_key_exchange.c
  library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c
  library/spdm_transport_mctp_lib/libspdm_mctp_mctp.c
  library/spdm_transport_pcidoe_lib/libspdm_doe_pcidoe.c
Labels: enhancement

#1696 Fix typo in GET_CERTIFICATE unit_test.
  unit_test/test_spdm_requester/get_certificate.c
Labels: refactor

#1699 Add unit test for Bad SlotID in CERTIFICATE message.
  unit_test/test_spdm_requester/get_certificate.c
  unit_test/test_spdm_responder/certificate.c
Labels: test

#1705 Add unit test for unrecommended OpaqueDataLength in CHALLENGE_AUTH message.
  unit_test/test_spdm_requester/challenge.c
Labels: test

#1713 Add unit tests for Invalid SlotID in KEY_EXCHANGE and KEY_EXCHANGE_RS…
  unit_test/test_spdm_requester/error_test/key_exchange_err.c
  unit_test/test_spdm_responder/key_exchange.c
Labels: test

#1722 Add LIBSPDM_CPU_ARM to fix armclang build error
  os_stub/openssllib/CMakeLists.txt
  os_stub/spdm_device_secret_lib_sample/CMakeLists.txt
Labels: bug

#1726 Check measurement_hash_type
  library/spdm_requester_lib/libspdm_req_challenge.c
  library/spdm_requester_lib/libspdm_req_key_exchange.c
  library/spdm_requester_lib/libspdm_req_psk_exchange.c
Labels: enhancement

#1727 Unconditionally check content_changed in MEASUREMENTS response
  library/spdm_requester_lib/libspdm_req_get_measurements.c
  unit_test/test_spdm_requester/error_test/get_measurements_err.c
Labels: enhancement

#1725 Initial rough draft for the Requester API documentation
  doc/api/requester_api.md
Labels: documentation

#1732 Fix spelling
  include/library/spdm_common_lib.h
  include/library/spdm_return_status.h
  library/spdm_common_lib/libspdm_com_context_data.c
  library/spdm_common_lib/libspdm_com_context_data_session.c
Labels: refactor

#1728 Fix incorrect error data.
  library/spdm_responder_lib/libspdm_rsp_challenge_auth.c
  library/spdm_responder_lib/libspdm_rsp_chunk_get.c
  library/spdm_responder_lib/libspdm_rsp_chunk_send_ack.c
  library/spdm_responder_lib/libspdm_rsp_digests.c
  library/spdm_responder_lib/libspdm_rsp_finish.c
  library/spdm_responder_lib/libspdm_rsp_heartbeat.c
  library/spdm_responder_lib/libspdm_rsp_key_exchange.c
  library/spdm_responder_lib/libspdm_rsp_measurements.c
  library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
  library/spdm_responder_lib/libspdm_rsp_psk_finish.c
  unit_test/test_spdm_responder/challenge_auth.c
  unit_test/test_spdm_responder/chunk_get.c
  unit_test/test_spdm_responder/chunk_send_ack.c
  unit_test/test_spdm_responder/digests.c
  unit_test/test_spdm_responder/finish.c
  unit_test/test_spdm_responder/measurements.c
  unit_test/test_spdm_responder/psk_finish.c
Labels: bug

#1715 Check transport length in libspdm_mctp_encode_message()
  library/spdm_transport_mctp_lib/libspdm_mctp_mctp.c
Labels: enhancement

#1714 Add delay time between retry requests
  include/internal/libspdm_common_lib.h
  include/internal/libspdm_requester_lib.h
  include/library/spdm_common_lib.h
  library/spdm_common_lib/libspdm_com_context_data.c
  library/spdm_requester_lib/libspdm_req_challenge.c
  library/spdm_requester_lib/libspdm_req_end_session.c
  library/spdm_requester_lib/libspdm_req_finish.c
  library/spdm_requester_lib/libspdm_req_get_capabilities.c
  library/spdm_requester_lib/libspdm_req_get_certificate.c
  library/spdm_requester_lib/libspdm_req_get_csr.c
  library/spdm_requester_lib/libspdm_req_get_digests.c
  library/spdm_requester_lib/libspdm_req_get_measurements.c
  library/spdm_requester_lib/libspdm_req_get_version.c
  library/spdm_requester_lib/libspdm_req_heartbeat.c
  library/spdm_requester_lib/libspdm_req_key_exchange.c
  library/spdm_requester_lib/libspdm_req_key_update.c
  library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c
  library/spdm_requester_lib/libspdm_req_psk_exchange.c
  library/spdm_requester_lib/libspdm_req_psk_finish.c
  library/spdm_requester_lib/libspdm_req_set_certificate.c
  os_stub/platform_lib/time_win.c
Labels: enhancement

#1745 Improve infinite loops
  os_stub/cryptlib_mbedtls/pk/x509.c
  os_stub/cryptlib_openssl/pk/x509.c
Labels: enhancement

#1747 Document target architecture
  doc/programming_environment.md
Labels: documentation

#1741 Fix incorrect use of UnsupportedRequest.
  library/spdm_responder_lib/libspdm_rsp_chunk_send_ack.c
  library/spdm_responder_lib/libspdm_rsp_measurements.c
  unit_test/test_spdm_responder/chunk_send_ack.c
  unit_test/test_spdm_responder/measurements.c
Labels: bug
