Repository DMTF/libspdm, pull requests merged in 2023-05, with the labels that each got.

#1999 support ct_exponent setting for peer
  library/spdm_common_lib/libspdm_com_context_data.c
Labels: enhancement

#2000 add check for GET_VERSION in session.
  library/spdm_responder_lib/libspdm_rsp_version.c
Labels: enhancement

#2006 Add handshake mode switch check in FINISH and PSK_FINISH.
  library/spdm_responder_lib/libspdm_rsp_finish.c
  library/spdm_responder_lib/libspdm_rsp_psk_finish.c
Labels: bug, security

#2007 Add handshake mode switch check in FINISH and PSK_FINISH.
  library/spdm_responder_lib/libspdm_rsp_finish.c
  library/spdm_responder_lib/libspdm_rsp_psk_finish.c
Labels: bug, security

#2014 Enforce DSP0277 capabilities
  library/spdm_requester_lib/libspdm_req_get_capabilities.c
  library/spdm_responder_lib/libspdm_rsp_capabilities.c
Labels: bug

#2011 os_stub/openssllib: Support more architectures
  os_stub/cryptlib_openssl/CMakeLists.txt
  os_stub/openssllib/CMakeLists.txt
Labels: enhancement

#2019 Requester need check RDTM
  library/spdm_requester_lib/libspdm_req_handle_error_response.c
  unit_test/test_spdm_requester/challenge.c
  unit_test/test_spdm_requester/end_session.c
  unit_test/test_spdm_requester/error_test/get_capabilities_err.c
  unit_test/test_spdm_requester/error_test/get_digests_err.c
  unit_test/test_spdm_requester/error_test/get_measurements_err.c
  unit_test/test_spdm_requester/error_test/get_version_err.c
  unit_test/test_spdm_requester/error_test/key_exchange_err.c
  unit_test/test_spdm_requester/error_test/negotiate_algorithms_err.c
  unit_test/test_spdm_requester/finish.c
  unit_test/test_spdm_requester/get_capabilities.c
  unit_test/test_spdm_requester/get_certificate.c
  unit_test/test_spdm_requester/get_digests.c
  unit_test/test_spdm_requester/get_measurements.c
  unit_test/test_spdm_requester/get_version.c
  unit_test/test_spdm_requester/heartbeat.c
  unit_test/test_spdm_requester/key_exchange.c
  unit_test/test_spdm_requester/key_update.c
  unit_test/test_spdm_requester/negotiate_algorithms.c
  unit_test/test_spdm_requester/psk_exchange.c
  unit_test/test_spdm_requester/psk_finish.c
Labels: bug, enhancement

#2028 fix running CI/CD, hit LIBSPDM_ ASSERT did not exit
  .github/workflows/build.yml
  os_stub/debuglib/debuglib.c
Labels: enhancement, test

#2034 Add FIPS to code coverage
  .github/workflows/code_coverage.yml
Labels: enhancement, test

#2027 Handle requester message too large
  include/library/spdm_return_status.h
  library/spdm_requester_lib/libspdm_req_send_receive.c
  unit_test/test_spdm_requester/chunk_send.c
Labels: bug

#2033 Provision peer's certificate chain buffer
  doc/user_guide.md
  include/internal/libspdm_common_lib.h
  include/library/spdm_common_lib.h
  include/library/spdm_responder_lib.h
  library/spdm_common_lib/libspdm_com_context_data.c
  library/spdm_responder_lib/libspdm_rsp_encap_get_certificate.c
  library/spdm_responder_lib/libspdm_rsp_encap_response.c
  library/spdm_responder_lib/libspdm_rsp_receive_send.c
  unit_test/fuzzing/test_responder/test_spdm_responder_encap_get_certificate/encap_get_certificate.c
  unit_test/fuzzing/test_responder/test_spdm_responder_key_exchange/key_exchange.c
  unit_test/spdm_unit_test_common/common.c
  unit_test/test_spdm_common/CMakeLists.txt
  unit_test/test_spdm_responder/encap_get_certificate.c
Labels: enhancement

#2035 Remove unneeded static cast
  os_stub/debuglib/debuglib.c
Labels: refactor

#2036 Add unit_test to cover return LIBSPDM_STATUS_PEER_BUFFER_TOO_SMALL case
  unit_test/test_spdm_requester/chunk_send.c
Labels: test

#2050 Change CSR format from pem to DER
  unit_test/sample_key/test_csr/Readme.txt
  unit_test/sample_key/test_csr/ecc256.key
  unit_test/sample_key/test_csr/ecc384.key
  unit_test/sample_key/test_csr/ecc521.key
  unit_test/sample_key/test_csr/ecp256.csr
  unit_test/sample_key/test_csr/ecp384.csr
  unit_test/sample_key/test_csr/ecp521.csr
  unit_test/sample_key/test_csr/rsa2048.csr
  unit_test/sample_key/test_csr/rsa2048.key
  unit_test/sample_key/test_csr/rsa3072.csr
  unit_test/sample_key/test_csr/rsa3072.key
  unit_test/sample_key/test_csr/rsa4096.csr
  unit_test/sample_key/test_csr/rsa4096.key
Labels: test

#2069 Prevent undefined behavior
  include/internal/libspdm_common_lib.h
  library/spdm_requester_lib/libspdm_req_get_capabilities.c
  library/spdm_requester_lib/libspdm_req_handle_error_response.c
  library/spdm_requester_lib/libspdm_req_send_receive.c
  library/spdm_responder_lib/libspdm_rsp_capabilities.c
  unit_test/test_spdm_requester/error_test/get_capabilities_err.c
  unit_test/test_spdm_responder/capabilities.c
Labels: security

#2070 Prevent undefined behavior
  include/internal/libspdm_common_lib.h
  library/spdm_requester_lib/libspdm_req_get_capabilities.c
  library/spdm_requester_lib/libspdm_req_handle_error_response.c
  library/spdm_requester_lib/libspdm_req_send_receive.c
  library/spdm_responder_lib/libspdm_rsp_capabilities.c
Labels: security
