Repository DMTF/libspdm, pull requests merged in 2023-04, with the labels that each got.

#1849 Check MCTP transport buffer size
  library/spdm_transport_mctp_lib/libspdm_mctp_common.c
  library/spdm_transport_mctp_lib/libspdm_mctp_mctp.c
Labels: enhancement

#1872 Fix ALGORITHMS related unit test issue.
  unit_test/test_spdm_responder/algorithms.c
Labels: test

#1846 library: spdm_requester: Pass along reset required error messages
  include/library/spdm_return_status.h
  library/spdm_requester_lib/libspdm_req_handle_error_response.c
  unit_test/test_spdm_requester/get_csr.c
  unit_test/test_spdm_requester/set_certificate.c
Labels: enhancement

#1908 Initial draft for secured message API
  doc/api/secured_message_api.md
Labels: documentation

#1921 Change assertion from `int` to `ptr`
  unit_test/test_spdm_common/context_data.c
Labels: bug

#1944 Fix missing CHUNK cap macro check.
  library/spdm_common_lib/libspdm_com_context_data.c
Labels: bug

#1948 Fix header documentation for `libspdm_get_leaf_cert_public_key_from_cert_chain`
  include/library/spdm_crypt_lib.h
Labels: bug, documentation

#1960 Fix wrong buffer size retrieving
  unit_test/test_spdm_responder/receive_send.c
Labels: bug

#1962 Initial draft for common API
  doc/api/common_api.md
  doc/api/requester_api.md
  doc/api/responder_api.md
Labels: documentation

#1963 Cleanup `spdm_secured_message_lib` header
  include/library/spdm_secured_message_lib.h
Labels: documentation, refactor

#1959 Fix arm build error when openssl is updated
  os_stub/cryptlib_openssl/CMakeLists.txt
Labels: bug

#1972 Add additional API documentation
  doc/api/common_api.md
  library/spdm_common_lib/libspdm_com_context_data.c
Labels: documentation, enhancement

#1975 Add check for slot_id
  library/spdm_common_lib/libspdm_com_context_data.c
Labels: enhancement

#1979 Fix unit_test using local variable as response
  unit_test/test_spdm_requester/encap_request.c
Labels: test

#1923 add check for transport for test.
  unit_test/spdm_transport_test_lib/common.c
  unit_test/spdm_transport_test_lib/test.c
Labels: test

#1990 Fix paramter order for IDE tooltip
  include/library/spdm_crypt_lib.h
  library/spdm_crypt_lib/libspdm_crypt_cert.c
Labels: bug, documentation

#1996 Need enhance the fuzzing test cases to improve the target code coverage
  unit_test/fuzzing/test_requester/test_spdm_requester_encap_certificate/encap_certificate.c
  unit_test/fuzzing/test_requester/test_spdm_requester_get_certificate/get_certificate.c
  unit_test/fuzzing/test_requester/test_spdm_requester_key_exchange/key_exchange.c
  unit_test/fuzzing/test_requester/test_spdm_requester_psk_exchange/psk_exchange.c
  unit_test/fuzzing/test_responder/test_spdm_responder_if_ready/respond_if_ready.c
  unit_test/fuzzing/test_responder/test_spdm_responder_key_exchange/key_exchange.c
  unit_test/fuzzing/test_responder/test_spdm_responder_psk_exchange_rsp/psk_exchange_rsp.c
  unit_test/fuzzing/test_responder/test_spdm_responder_psk_finish_rsp/psk_finish_rsp.c
Labels: test
