Repository DMTF/libspdm, pull requests merged in 2023-01, with the labels that each got.

#1564 Fix macro usage
  unit_test/test_crypt/rsa_verify.c
Labels: test

#1558 Make the mbedtls gen csr return right
  os_stub/cryptlib_mbedtls/pk/x509.c
Labels: bug

#1569 Remove function pointers from DHE cryptography in spdm_crypt_lib
  library/spdm_crypt_lib/libspdm_crypt_dhe.c
Labels: enhancement, security

#1570 Update documentation for 2.3 release
  README.md
  doc/build.md
  doc/design.md
  doc/test.md
  doc/user_guide.md
  include/library/spdm_common_lib.h
  include/library/spdm_lib_config.h
  library/spdm_common_lib/libspdm_com_context_data.c
Labels: documentation, refactor

#1575 Add comments for newly added macros
  include/library/spdm_lib_config.h
Labels: documentation, enhancement

#1571 Update VERSION.md for 2.3 release
  VERSION.md
Labels: documentation

#1578 Update VERSION.md to 3.0 after 2.3 release
  VERSION.md
Labels: documentation

#1584 Change Client/Server to Requester/Responder
  library/spdm_requester_lib/libspdm_req_challenge.c
  library/spdm_requester_lib/libspdm_req_get_measurements.c
  library/spdm_requester_lib/libspdm_req_key_exchange.c
  library/spdm_requester_lib/libspdm_req_psk_exchange.c
  library/spdm_responder_lib/libspdm_rsp_encap_challenge.c
Labels: refactor

#1583 Change function pointer type from size_t to void *
  include/internal/libspdm_common_lib.h
  library/spdm_requester_lib/libspdm_req_encap_request.c
  library/spdm_responder_lib/libspdm_rsp_receive_send.c
Labels: bug

#1576 Add FIPS 140-3 config for libspdm
  include/library/spdm_lib_config.h
Labels: enhancement, security

#1593 Remove the checking of extended_key_usage
  library/spdm_crypt_lib/libspdm_crypt_cert.c
Labels: bug

#1598 Add concurrency to build and test action
  .github/workflows/build.yml
Labels: enhancement, test

#1596 Remove multiple callback functions
  include/internal/libspdm_common_lib.h
  include/library/spdm_lib_config.h
  include/library/spdm_responder_lib.h
  library/spdm_responder_lib/libspdm_rsp_receive_send.c
Labels: enhancement

#1599 Initial draft for programming environment document
  doc/programming_environment.md
Labels: documentation

#1602 Initial commit for libspdm_check_context
  include/library/spdm_common_lib.h
  include/library/spdm_lib_config.h
  library/spdm_common_lib/libspdm_com_context_data.c
  unit_test/test_spdm_common/context_data.c
Labels: enhancement

#1609 Capitalize libspdm_context_struct_version
  include/internal/libspdm_common_lib.h
  library/spdm_common_lib/libspdm_com_context_data.c
Labels: refactor

#1608 Fix bug when checking Requester's capabilities
  VERSION.md
  library/spdm_responder_lib/libspdm_rsp_capabilities.c
  unit_test/test_spdm_responder/capabilities.c
Labels: bug

#1616 Remove illegal capabilities checks
  library/spdm_responder_lib/libspdm_rsp_capabilities.c
  unit_test/test_spdm_responder/capabilities.c
Labels: bug

#1625 Add check for new dhe_context
  library/spdm_responder_lib/libspdm_rsp_key_exchange.c
Labels: enhancement, security

#1630 Remove deprecated macros
  include/internal/libspdm_common_lib.h
  include/internal/libspdm_lib_config.h
  include/internal/libspdm_responder_lib.h
  include/library/spdm_requester_lib.h
  library/spdm_common_lib/libspdm_com_context_data.c
  library/spdm_requester_lib/libspdm_req_handle_error_response.c
  library/spdm_requester_lib/libspdm_req_send_receive.c
  library/spdm_requester_lib/libspdm_req_set_certificate.c
  library/spdm_responder_lib/libspdm_rsp_chunk_get.c
  library/spdm_responder_lib/libspdm_rsp_chunk_send_ack.c
  library/spdm_responder_lib/libspdm_rsp_communication.c
  library/spdm_responder_lib/libspdm_rsp_receive_send.c
  library/spdm_responder_lib/libspdm_rsp_set_certificate.c
Labels: refactor

#1633 Change request retry times to a runtime parameter
  include/library/spdm_common_lib.h
  include/library/spdm_lib_config.h
  library/spdm_common_lib/libspdm_com_context_data.c
  unit_test/test_spdm_requester/challenge.c
  unit_test/test_spdm_requester/end_session.c
  unit_test/test_spdm_requester/finish.c
  unit_test/test_spdm_requester/get_capabilities.c
  unit_test/test_spdm_requester/get_certificate.c
  unit_test/test_spdm_requester/get_measurements.c
  unit_test/test_spdm_requester/get_version.c
  unit_test/test_spdm_requester/heartbeat.c
  unit_test/test_spdm_requester/key_exchange.c
  unit_test/test_spdm_requester/key_update.c
  unit_test/test_spdm_requester/negotiate_algorithms.c
  unit_test/test_spdm_requester/psk_exchange.c
  unit_test/test_spdm_requester/psk_finish.c
Labels: enhancement

#1637 Delete unneeded assignment to 0
  library/spdm_common_lib/libspdm_com_context_data.c
Labels: refactor

#1581 Add more check for supported algorithm
  include/internal/libspdm_macro_check.h
Labels: enhancement, security

#1638 Make RESPOND_IF_READY a compile-time capability
  .github/workflows/build.yml
  include/library/spdm_common_lib.h
  include/library/spdm_lib_config.h
  library/spdm_requester_lib/libspdm_req_handle_error_response.c
  library/spdm_responder_lib/libspdm_rsp_handle_response_state.c
  library/spdm_responder_lib/libspdm_rsp_receive_send.c
  library/spdm_responder_lib/libspdm_rsp_respond_if_ready.c
  unit_test/fuzzing/test_responder/test_spdm_responder_encap_response/encap_response.c
  unit_test/fuzzing/test_responder/test_spdm_responder_if_ready/respond_if_ready.c
  unit_test/fuzzing/test_responder/test_spdm_responder_psk_exchange_rsp/psk_exchange_rsp.c
  unit_test/test_spdm_requester/challenge.c
  unit_test/test_spdm_requester/end_session.c
  unit_test/test_spdm_requester/finish.c
  unit_test/test_spdm_requester/get_certificate.c
  unit_test/test_spdm_requester/get_measurements.c
  unit_test/test_spdm_requester/heartbeat.c
  unit_test/test_spdm_requester/key_exchange.c
  unit_test/test_spdm_requester/key_update.c
  unit_test/test_spdm_requester/psk_exchange.c
  unit_test/test_spdm_requester/psk_finish.c
  unit_test/test_spdm_responder/certificate.c
  unit_test/test_spdm_responder/challenge_auth.c
  unit_test/test_spdm_responder/digests.c
  unit_test/test_spdm_responder/end_session.c
  unit_test/test_spdm_responder/finish.c
  unit_test/test_spdm_responder/heartbeat.c
  unit_test/test_spdm_responder/key_exchange.c
  unit_test/test_spdm_responder/key_update.c
  unit_test/test_spdm_responder/measurements.c
  unit_test/test_spdm_responder/psk_exchange.c
  unit_test/test_spdm_responder/psk_finish.c
  unit_test/test_spdm_responder/respond_if_ready.c
  unit_test/test_spdm_responder/test_spdm_responder.c
Labels: enhancement

#1645 test_crypt: wrapper SHA256 by LIBSPDM_SHA256_SUPPORT_TEST.
  unit_test/test_crypt/rsa_verify.c
Labels: test

#1643 test_crypt should not link spdm_device_secret_lib_sample.
  unit_test/test_crypt/CMakeLists.txt
  unit_test/test_crypt/test_crypt.c
  unit_test/test_crypt/test_crypt.h
  unit_test/test_crypt/x509_verify.c
Labels: test

#1654 Fix typo
  library/spdm_crypt_lib/libspdm_crypt_cert.c
Labels: refactor

#1653 Change parameter order
  include/library/spdm_requester_lib.h
  library/spdm_requester_lib/libspdm_req_get_csr.c
  library/spdm_requester_lib/libspdm_req_set_certificate.c
  unit_test/fuzzing/test_requester/test_spdm_requester_get_csr/get_csr.c
  unit_test/fuzzing/test_requester/test_spdm_requester_set_certificate/set_certificate.c
  unit_test/test_spdm_requester/get_csr.c
  unit_test/test_spdm_requester/set_certificate.c
Labels: refactor

#1658 Add message logging to more messages
  library/spdm_requester_lib/libspdm_req_end_session.c
  library/spdm_requester_lib/libspdm_req_finish.c
  library/spdm_requester_lib/libspdm_req_get_certificate.c
  library/spdm_requester_lib/libspdm_req_get_digests.c
  library/spdm_requester_lib/libspdm_req_heartbeat.c
  library/spdm_requester_lib/libspdm_req_key_exchange.c
  library/spdm_requester_lib/libspdm_req_key_update.c
  library/spdm_requester_lib/libspdm_req_psk_exchange.c
  library/spdm_requester_lib/libspdm_req_psk_finish.c
  library/spdm_requester_lib/libspdm_req_set_certificate.c
Labels: enhancement

#1665 Fix spelling errors in comments
  include/hal/library/cryptlib/cryptlib_cert.h
  include/internal/libspdm_common_lib.h
  include/library/spdm_common_lib.h
  include/library/spdm_crypt_lib.h
  include/library/spdm_lib_config.h
  include/library/spdm_requester_lib.h
  library/spdm_common_lib/libspdm_com_context_data.c
  library/spdm_common_lib/libspdm_com_crypto_service.c
  library/spdm_common_lib/libspdm_com_crypto_service_session.c
  library/spdm_requester_lib/libspdm_req_get_digests.c
  library/spdm_responder_lib/libspdm_rsp_algorithms.c
Labels: documentation, refactor

#1676 Print CMake version in CI/CD
  .github/workflows/build.yml
Labels: enhancement, test
