Repository DMTF/libspdm, pull requests merged in 2023-07, with the labels that each got.

#2198 Fix message logging bugs
  include/library/spdm_common_lib.h
  library/spdm_common_lib/libspdm_com_context_data.c
  library/spdm_requester_lib/libspdm_req_send_receive.c
Labels: bug

#2201 Create 3.0 change log
  doc/changelog.md
Labels: documentation, enhancement

#2200 Retrieve NSPI from spdm_context without session ID
  doc/api/common_api.md
  include/internal/libspdm_common_lib.h
  library/spdm_common_lib/libspdm_com_context_data.c
  library/spdm_responder_lib/libspdm_rsp_end_session.c
  unit_test/test_spdm_responder/end_session.c
Labels: enhancement

#2214 Update clang build README
  README.md
Labels: documentation

#2231 Clean up user guide.
  doc/user_guide.md
Labels: documentation

#2232 clean up change log.
  doc/changelog.md
Labels: documentation

#2221 Add FIPS doc
  doc/fips.md
Labels: documentation

#2222 Add endianness clarification.
  doc/crypto_endianness.md
Labels: documentation

#2234 Add raw public key doc.
  doc/raw_public_key.md
Labels: documentation

#2239 Document `MAX_SPDM_SESSION_SEQUENCE_NUMBER`
  doc/api/common_api.md
Labels: documentation

#2240 Document assertions
  doc/programming_environment.md
Labels: documentation

#2236 Add AEAD limit doc
  doc/aead_limit.md
Labels: documentation

#2243 Allow Integrator to query the AEAD sequence number
  doc/api/common_api.md
  include/library/spdm_common_lib.h
  library/spdm_common_lib/libspdm_com_context_data.c
Labels: enhancement

#2249 Add request code assertions
  library/spdm_responder_lib/libspdm_rsp_algorithms.c
  library/spdm_responder_lib/libspdm_rsp_capabilities.c
  library/spdm_responder_lib/libspdm_rsp_certificate.c
  library/spdm_responder_lib/libspdm_rsp_challenge_auth.c
  library/spdm_responder_lib/libspdm_rsp_csr.c
  library/spdm_responder_lib/libspdm_rsp_digests.c
  library/spdm_responder_lib/libspdm_rsp_finish.c
  library/spdm_responder_lib/libspdm_rsp_heartbeat.c
  library/spdm_responder_lib/libspdm_rsp_key_exchange.c
  library/spdm_responder_lib/libspdm_rsp_key_update.c
  library/spdm_responder_lib/libspdm_rsp_measurements.c
  library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
  library/spdm_responder_lib/libspdm_rsp_psk_finish.c
  library/spdm_responder_lib/libspdm_rsp_respond_if_ready.c
  library/spdm_responder_lib/libspdm_rsp_set_certificate.c
  library/spdm_responder_lib/libspdm_rsp_version.c
Labels: enhancement

#2250 Ensure error version of 1.0
  library/spdm_responder_lib/libspdm_rsp_version.c
  unit_test/test_spdm_responder/version.c
Labels: bug

#2251 Use correct return type
  os_stub/cryptlib_mbedtls/cipher/aead_aes_gcm.c
  os_stub/cryptlib_mbedtls/cipher/aead_chacha20_poly1305.c
  os_stub/cryptlib_mbedtls/der/der.c
  os_stub/cryptlib_mbedtls/hash/sha.c
  os_stub/cryptlib_mbedtls/hmac/hmac_sha.c
  os_stub/cryptlib_mbedtls/kdf/hkdf_sha.c
  os_stub/cryptlib_mbedtls/pem/pem.c
  os_stub/cryptlib_mbedtls/pk/dh.c
  os_stub/cryptlib_mbedtls/pk/ec.c
  os_stub/cryptlib_mbedtls/pk/rsa_basic.c
  os_stub/cryptlib_mbedtls/pk/rsa_ext.c
  os_stub/cryptlib_mbedtls/pk/x509.c
Labels: bug

#2261 Add more clarification for AEAD limit.
  doc/aead_limit.md
Labels: documentation

#2263 Fix FIPS document
  doc/fips.md
Labels: documentation

#2265 Correct the secured message version macros in unit tests.
  unit_test/fuzzing/test_requester/test_spdm_requester_key_exchange/key_exchange.c
  unit_test/fuzzing/test_requester/test_spdm_requester_psk_exchange/psk_exchange.c
  unit_test/fuzzing/test_spdm_common/test_process_opaque_data/test_process_opaque_data_supported_version_data.c
  unit_test/test_spdm_common/context_data.c
  unit_test/test_spdm_requester/error_test/key_exchange_err.c
  unit_test/test_spdm_requester/key_exchange.c
  unit_test/test_spdm_requester/psk_exchange.c
Labels: test

#2262 Add more doc to readme.
  README.md
Labels: documentation

#2264 Allow no selected OpaqueDataFmt
  include/industry_standard/spdm.h
  include/library/spdm_return_status.h
  library/spdm_requester_lib/libspdm_req_challenge.c
  library/spdm_requester_lib/libspdm_req_get_csr.c
  library/spdm_requester_lib/libspdm_req_get_measurements.c
  library/spdm_requester_lib/libspdm_req_key_exchange.c
  library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c
  library/spdm_requester_lib/libspdm_req_psk_exchange.c
  library/spdm_responder_lib/libspdm_rsp_algorithms.c
  library/spdm_responder_lib/libspdm_rsp_challenge_auth.c
  library/spdm_responder_lib/libspdm_rsp_csr.c
  library/spdm_responder_lib/libspdm_rsp_key_exchange.c
  library/spdm_responder_lib/libspdm_rsp_measurements.c
  library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
  unit_test/test_spdm_requester/error_test/negotiate_algorithms_err.c
  unit_test/test_spdm_requester/get_csr.c
  unit_test/test_spdm_requester/key_exchange.c
  unit_test/test_spdm_requester/psk_exchange.c
  unit_test/test_spdm_responder/algorithms.c
  unit_test/test_spdm_responder/csr.c
  unit_test/test_spdm_responder/key_exchange.c
  unit_test/test_spdm_responder/measurements.c
  unit_test/test_spdm_responder/psk_exchange.c
Labels: enhancement

#2273 Move `libspdm_verify_peer_cert_chain_buffer` to unit_test
  include/internal/libspdm_common_lib.h
  library/spdm_common_lib/libspdm_com_crypto_service.c
  unit_test/test_spdm_common/context_data.c
Labels: refactor
