Repository DMTF/libspdm, pull requests merged in 2023-09, with the labels that each got.

#2361 Add little-endian to big-endian function
  include/internal/libspdm_common_lib.h
  unit_test/test_spdm_common/CMakeLists.txt
  unit_test/test_spdm_common/support.c
  unit_test/test_spdm_common/test_spdm_common.c
Labels: enhancement

#2366 cryptlib_openssl: x509: fixup return value usage
  os_stub/cryptlib_openssl/pk/x509.c
Labels: bug

#2365 Enable signing as little endian in secret_lib_sample.
  os_stub/spdm_device_secret_lib_sample/lib.c
  os_stub/spdm_device_secret_lib_sample/spdm_device_secret_lib_internal.h
Labels: enhancement

#2367 Add unit tests for big-little-endian signature verification
  unit_test/test_spdm_crypt/CMakeLists.txt
  unit_test/test_spdm_crypt/test_spdm_crypt.c
Labels: test

#2357 Specify sequence number endianness
  include/internal/libspdm_common_lib.h
  include/internal/libspdm_secured_message_lib.h
  include/library/spdm_common_lib.h
  library/spdm_common_lib/libspdm_com_context_data.c
  library/spdm_common_lib/libspdm_com_context_data_session.c
  library/spdm_secured_message_lib/libspdm_secmes_context_data.c
  library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c
Labels: enhancement
