Repository DMTF/libspdm, pull requests merged in 2024-05, with the labels that each got.

#2684 Create LICENSE.md
  LICENSE.md
Labels: documentation

#2680 Fix req_vendor_id and req_size duplication
  library/spdm_responder_lib/libspdm_rsp_vendor_response.c
Labels: bug

#2687 Merge test_spdm_vendor_cmds into test_spdm_requester or test_spdm_res…
  CMakeLists.txt
  unit_test/test_spdm_requester/CMakeLists.txt
  unit_test/test_spdm_requester/error_test/vendor_request_err.c
  unit_test/test_spdm_requester/test_spdm_requester.c
  unit_test/test_spdm_requester/vendor_request.c
  unit_test/test_spdm_responder/CMakeLists.txt
  unit_test/test_spdm_responder/error_test/vendor_response_err.c
  unit_test/test_spdm_responder/test_spdm_responder.c
  unit_test/test_spdm_responder/vendor_response.c
  unit_test/test_spdm_vendor_cmds/CMakeLists.txt
  unit_test/test_spdm_vendor_cmds/test_spdm_vendor_cmds.c
Labels: test

#2691 Rectify the four-byte alignment issue in the fuzzy testing.
  unit_test/fuzzing/spdm_unit_fuzzing_common/toolchain_harness.c
Labels: test

#2693 Fix cert verify logic in rsp_encap_get_certificate
  library/spdm_responder_lib/libspdm_rsp_encap_get_certificate.c
Labels: bug

#2699 Update cmocka version file
  unit_test/cmockalib/version.txt
Labels: documentation

#2672 Add verify cert callback function for DiceTcbInfo
  CMakeLists.txt
  os_stub/spdm_cert_verify_callback_sample/CMakeLists.txt
  os_stub/spdm_cert_verify_callback_sample/README.md
  os_stub/spdm_cert_verify_callback_sample/spdm_cert_verify_callback.c
  os_stub/spdm_cert_verify_callback_sample/spdm_cert_verify_callback_internal.h
  unit_test/test_spdm_sample/CMakeLists.txt
  unit_test/test_spdm_sample/test_spdm_sample.c
Labels: test

#2702 Fix acquiring Session ID in Vendor Defined Response
  library/spdm_responder_lib/libspdm_rsp_vendor_response.c
Labels: bug

#2706 Fix vendor response test case issues
  unit_test/test_spdm_responder/error_test/vendor_response_err.c
  unit_test/test_spdm_responder/vendor_response.c
Labels: test

#2710 Update cmocka submodule to gitlab
  .gitmodules
Labels: test

#2705 Add "extern C" to library headers
  include/library/spdm_common_lib.h
  include/library/spdm_crypt_lib.h
  include/library/spdm_requester_lib.h
  include/library/spdm_responder_lib.h
  include/library/spdm_return_status.h
  include/library/spdm_secured_message_lib.h
  include/library/spdm_transport_mctp_lib.h
  include/library/spdm_transport_pcidoe_lib.h
Labels: enhancement
