Repository DMTF/libspdm, pull requests merged in 2024-08, with the labels that each got.

#2781 libspdm_req_get_measurements: Check the length of all measurements
  library/spdm_requester_lib/libspdm_req_get_measurements.c
Labels: enhancement

#2786 fix test case measurements
  unit_test/test_spdm_responder/measurements.c
Labels: bug, test

#2789 Move null implementation of libspdm_event_get_types
  os_stub/spdm_device_secret_lib_null/lib.c
Labels: bug

#2797 Fix default build options for initialize_secured_message_context()
  unit_test/test_spdm_secured_message/encode_decode.c
  unit_test/test_spdm_secured_message/test_spdm_secured_message.c
Labels: bug

#2798 Add secure messages to test coverage
  .github/workflows/code_coverage.yml
Labels: test

#2801 Specify SPDM certificate chain structure
  doc/api/common_api.md
  include/industry_standard/spdm.h
Labels: documentation

#2804 Add retvals to libspdm_get_random_number
  include/library/spdm_crypt_lib.h
Labels: documentation

#2806 Update CodeQL actions
  .github/workflows/codeql-analysis.yml
Labels: test, build

#2802 Mask capability flags based on negotiated version
  include/internal/libspdm_common_lib.h
  library/spdm_common_lib/libspdm_com_support.c
  library/spdm_requester_lib/libspdm_req_get_capabilities.c
  library/spdm_responder_lib/libspdm_rsp_capabilities.c
Labels: bug

#2809 Setup nightly Coverity scanning
  .github/workflows/coverity.yml
Labels: test, build

#2811 Fix unused value Coverity types
  library/spdm_common_lib/libspdm_com_context_data.c
  library/spdm_requester_lib/libspdm_req_handle_error_response.c
  library/spdm_requester_lib/libspdm_req_send_receive.c
Labels: refactor

#2813 Change logical negation to bitwise negation
  unit_test/test_spdm_requester/encap_key_update.c
Labels: bug, test

#2815 remove redundant retry count check found by coverity
  library/spdm_requester_lib/libspdm_req_challenge.c
  library/spdm_requester_lib/libspdm_req_end_session.c
  library/spdm_requester_lib/libspdm_req_finish.c
  library/spdm_requester_lib/libspdm_req_get_capabilities.c
  library/spdm_requester_lib/libspdm_req_get_certificate.c
  library/spdm_requester_lib/libspdm_req_get_csr.c
  library/spdm_requester_lib/libspdm_req_get_digests.c
  library/spdm_requester_lib/libspdm_req_get_event_types.c
  library/spdm_requester_lib/libspdm_req_get_measurement_extension_log.c
  library/spdm_requester_lib/libspdm_req_get_measurements.c
  library/spdm_requester_lib/libspdm_req_get_version.c
  library/spdm_requester_lib/libspdm_req_heartbeat.c
  library/spdm_requester_lib/libspdm_req_key_exchange.c
  library/spdm_requester_lib/libspdm_req_key_update.c
  library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c
  library/spdm_requester_lib/libspdm_req_psk_exchange.c
  library/spdm_requester_lib/libspdm_req_psk_finish.c
  library/spdm_requester_lib/libspdm_req_set_certificate.c
  library/spdm_requester_lib/libspdm_req_vendor_request.c
Labels: refactor
