Repository DMTF/libspdm, pull requests merged in 2024-09, with the labels that each got.

#2822 Change spdm_test_context to spdm_context in unit test
  unit_test/test_spdm_requester/error_test/vendor_request_err.c
  unit_test/test_spdm_requester/vendor_request.c
Labels: bug, test

#2817 Add unit tests and fuzz tests for get_key_pair_info
  CMakeLists.txt
  unit_test/fuzzing/fuzzing_AFL.sh
  unit_test/fuzzing/fuzzing_AFLTurbo.sh
  unit_test/fuzzing/fuzzing_AFLplusplus.sh
  unit_test/fuzzing/fuzzing_LibFuzzer.sh
  unit_test/fuzzing/oss_fuzz.sh
  unit_test/fuzzing/run_initial_seed.sh
  unit_test/fuzzing/seeds/test_spdm_requester_get_key_pair_info/key_pair_info.raw
  unit_test/fuzzing/seeds/test_spdm_responder_key_pair_info/key_pair_info.raw
  unit_test/fuzzing/test_requester/test_spdm_requester_get_key_pair_info/CMakeLists.txt
  unit_test/fuzzing/test_requester/test_spdm_requester_get_key_pair_info/get_key_pair_info.c
  unit_test/fuzzing/test_responder/test_spdm_responder_key_pair_info/CMakeLists.txt
  unit_test/fuzzing/test_responder/test_spdm_responder_key_pair_info/key_pair_info.c
  unit_test/test_spdm_requester/get_key_pair_info.c
  unit_test/test_spdm_responder/key_pair_info.c
Labels: test

#2832 Skip certificate algorithm check
  library/spdm_crypt_lib/libspdm_crypt_cert.c
Labels: bug

#2829 Cleanup DOE header
  include/industry_standard/pcidoe.h
Labels: documentation

#2840 Run code coverage weekly
  .github/workflows/code_coverage.yml
Labels: test

#2835 Add unit tests and fuzz tests for set_key_pair_info
  CMakeLists.txt
  unit_test/fuzzing/fuzzing_AFL.sh
  unit_test/fuzzing/fuzzing_AFLTurbo.sh
  unit_test/fuzzing/fuzzing_AFLplusplus.sh
  unit_test/fuzzing/fuzzing_LibFuzzer.sh
  unit_test/fuzzing/oss_fuzz.sh
  unit_test/fuzzing/run_initial_seed.sh
  unit_test/fuzzing/seeds/test_spdm_requester_set_key_pair_info/set_key_pair_info_response.raw
  unit_test/fuzzing/seeds/test_spdm_responder_set_key_pair_info_ack/set_key_pair_info_request.raw
  unit_test/fuzzing/test_requester/test_spdm_requester_set_key_pair_info/CMakeLists.txt
  unit_test/fuzzing/test_requester/test_spdm_requester_set_key_pair_info/set_key_pair_info.c
  unit_test/fuzzing/test_responder/test_spdm_responder_set_key_pair_info_ack/CMakeLists.txt
  unit_test/fuzzing/test_responder/test_spdm_responder_set_key_pair_info_ack/set_key_pair_info_ack.c
  unit_test/test_spdm_requester/set_key_pair_info.c
  unit_test/test_spdm_responder/set_key_pair_info_ack.c
Labels: test

#2837 Skip keyUsage check for AliasCert and SET_CERTIFICATE
  library/spdm_crypt_lib/libspdm_crypt_cert.c
Labels: bug

#2848 Do not use SPDM_ERROR_CODE_SESSION_REQUIRED for SPDM 1.1.
  library/spdm_responder_lib/libspdm_rsp_end_session.c
  library/spdm_responder_lib/libspdm_rsp_finish.c
  library/spdm_responder_lib/libspdm_rsp_heartbeat.c
  library/spdm_responder_lib/libspdm_rsp_key_update.c
  library/spdm_responder_lib/libspdm_rsp_psk_finish.c
Labels: bug

#2851 Add variable for format specifier
  os_stub/spdm_device_secret_lib_sample/lib.c
Labels: bug

#2852 Remove cast-align for RISC-V
  CMakeLists.txt
Labels: build
