Repository DMTF/libspdm, pull requests merged in 2024-06, with the labels that each got.

#2718 Add length check during verify cert chain
  os_stub/cryptlib_mbedtls/pk/x509.c
  os_stub/cryptlib_openssl/pk/x509.c
  unit_test/test_crypt/x509_verify.c
  unit_test/test_spdm_crypt/test_spdm_crypt.c
Labels: enhancement

#2728 Fix typo in 'README.md'.
  README.md
Labels: bug, documentation

#2729 Fix wrong release_receiver_buffer before acquire
  library/spdm_requester_lib/libspdm_req_vendor_request.c
Labels: bug

#2730 Fix some typo for include folder
  include/hal/library/cryptlib/cryptlib_cert.h
  include/hal/library/responder/csrlib.h
  include/industry_standard/pcidoe.h
  include/internal/libspdm_common_lib.h
  include/internal/libspdm_requester_lib.h
  include/library/spdm_common_lib.h
  include/library/spdm_requester_lib.h
  library/spdm_common_lib/libspdm_com_context_data.c
  library/spdm_common_lib/libspdm_com_opaque_data.c
  library/spdm_requester_lib/libspdm_req_encap_digests.c
  library/spdm_requester_lib/libspdm_req_get_csr.c
  os_stub/cryptlib_mbedtls/pk/x509.c
  os_stub/cryptlib_null/pk/x509.c
  os_stub/cryptlib_openssl/pk/x509.c
Labels: bug, documentation

#2738 Cleanup spdm_lib_config.h
  include/library/spdm_lib_config.h
Labels: documentation, enhancement
