Repository DMTF/libspdm, pull requests merged in 2024-11, with the labels that each got.

#2876 More descriptive buffer error codes
  library/spdm_requester_lib/libspdm_req_send_receive.c
Labels: enhancement

#2883 Update CodeQL version from 2 to 3
  .github/workflows/cifuzz.yml
Labels: test

#2878 Refactor send/receive part 1
  library/spdm_requester_lib/libspdm_req_send_receive.c
  library/spdm_responder_lib/libspdm_rsp_receive_send.c
Labels: refactor

#2886 Fix typo in SET_CERTIFICATE unit test
  unit_test/test_spdm_responder/set_certificate_rsp.c
Labels: refactor

#2885 Create CODEOWNERS
  .github/CODEOWNERS
Labels: enhancement

#2887 Fix the failure of test_spdm_responder when it is run multiple times.
  unit_test/test_spdm_responder/set_key_pair_info_ack.c
Labels: bug, test

#2898 fix incorrect size check in libspdm_get_local_public_key_buffer.
  library/spdm_common_lib/libspdm_com_crypto_service.c
Labels: bug

#2897 Implement MbedTLS wrappers for SHA3 hash, HMAC and HKDF
  CMakeLists.txt
  os_stub/cryptlib_mbedtls/hash/sha3.c
  os_stub/cryptlib_mbedtls/hmac/hmac_sha3.c
  os_stub/cryptlib_mbedtls/kdf/hkdf_sha3.c
  os_stub/cryptlib_mbedtls/pk/ec.c
  os_stub/cryptlib_mbedtls/pk/rsa_basic.c
  os_stub/cryptlib_mbedtls/pk/rsa_ext.c
  os_stub/cryptlib_mbedtls/pk/x509.c
Labels: enhancement

#2899 Restrict x86 mnemonic to x86-64
  os_stub/debuglib/debuglib.c
Labels: enhancement

#2906 Change "sample" to "reference"
  README.md
Labels: documentation

#2910 Reorganize `spdm_device_secret_lib_sample`
  os_stub/spdm_device_secret_lib_sample/CMakeLists.txt
  os_stub/spdm_device_secret_lib_sample/chal.c
  os_stub/spdm_device_secret_lib_sample/csr.c
  os_stub/spdm_device_secret_lib_sample/event.c
  os_stub/spdm_device_secret_lib_sample/key_pair.c
  os_stub/spdm_device_secret_lib_sample/lib.c
  os_stub/spdm_device_secret_lib_sample/meas.c
  os_stub/spdm_device_secret_lib_sample/psk.c
  os_stub/spdm_device_secret_lib_sample/read_priv_key_pem.c
  os_stub/spdm_device_secret_lib_sample/read_priv_key_raw_data.c
  os_stub/spdm_device_secret_lib_sample/read_pub_cert.c
  os_stub/spdm_device_secret_lib_sample/read_pub_key_der.c
  os_stub/spdm_device_secret_lib_sample/read_special_cert.c
  os_stub/spdm_device_secret_lib_sample/set_cert.c
  os_stub/spdm_device_secret_lib_sample/sign.c
  os_stub/spdm_device_secret_lib_sample/spdm_device_secret_lib_internal.h
Labels: refactor

#2912 Clean up encapsulated send and receive
  library/spdm_requester_lib/libspdm_req_encap_request.c
  library/spdm_responder_lib/libspdm_rsp_encap_response.c
Labels: refactor
