Repository DMTF/libspdm, pull requests merged in 2024-02, with the labels that each got.

#2555 Fix debug message
  library/spdm_requester_lib/libspdm_req_key_update.c
Labels: bug

#2563 Provide rationale for `LIBSPDM_MAX_CT_EXPONENT `
  include/internal/libspdm_common_lib.h
Labels: documentation

#2558 Enhance `debuglib` checking
  os_stub/debuglib/debuglib.c
Labels: enhancement, test

#2559 Enhance unit test for OtherParamsSupport field algorithm negotiate
  unit_test/test_spdm_requester/negotiate_algorithms.c
  unit_test/test_spdm_responder/algorithms.c
Labels: test

#2574 Fix conversion specifiers
  library/spdm_common_lib/libspdm_com_context_data.c
  library/spdm_common_lib/libspdm_com_msg_log.c
  library/spdm_common_lib/libspdm_com_support.c
  library/spdm_requester_lib/libspdm_req_challenge.c
  library/spdm_requester_lib/libspdm_req_communication.c
  library/spdm_requester_lib/libspdm_req_finish.c
  library/spdm_requester_lib/libspdm_req_get_digests.c
  library/spdm_requester_lib/libspdm_req_get_measurements.c
  library/spdm_requester_lib/libspdm_req_key_exchange.c
  library/spdm_requester_lib/libspdm_req_psk_exchange.c
  library/spdm_requester_lib/libspdm_req_send_receive.c
  library/spdm_responder_lib/libspdm_rsp_encap_challenge.c
  library/spdm_responder_lib/libspdm_rsp_encap_get_digests.c
  library/spdm_responder_lib/libspdm_rsp_key_exchange.c
  library/spdm_responder_lib/libspdm_rsp_receive_send.c
  library/spdm_secured_message_lib/libspdm_secmes_session.c
  library/spdm_transport_mctp_lib/libspdm_mctp_common.c
  library/spdm_transport_pcidoe_lib/libspdm_doe_common.c
  unit_test/fuzzing/test_requester/test_spdm_requester_get_csr/get_csr.c
  unit_test/fuzzing/test_requester/test_spdm_requester_key_exchange/key_exchange.c
  unit_test/fuzzing/test_requester/test_spdm_requester_psk_exchange/psk_exchange.c
  unit_test/fuzzing/test_requester/test_spdm_requester_set_certificate/set_certificate.c
  unit_test/spdm_transport_test_lib/common.c
  unit_test/test_crypt/x509_verify.c
  unit_test/test_size/test_size_of_spdm_requester/spdm_requester_init.c
  unit_test/test_size/test_size_of_spdm_requester/spdm_requester_session.c
  unit_test/test_spdm_requester/challenge.c
  unit_test/test_spdm_requester/chunk_get.c
  unit_test/test_spdm_requester/encap_request.c
  unit_test/test_spdm_requester/error_test/get_measurements_err.c
  unit_test/test_spdm_requester/error_test/key_exchange_err.c
  unit_test/test_spdm_requester/get_capabilities.c
  unit_test/test_spdm_requester/get_certificate.c
  unit_test/test_spdm_requester/get_measurements.c
  unit_test/test_spdm_requester/get_version.c
  unit_test/test_spdm_requester/key_exchange.c
  unit_test/test_spdm_requester/key_update.c
  unit_test/test_spdm_requester/psk_exchange.c
  unit_test/test_spdm_requester/set_certificate.c
Labels: bug

#2578 CMakeLists: add disabling flto option for NONE
  CMakeLists.txt
Labels: build

#2579 Enhance unit test for OPAQUE_DATA_FORMAT algorithm
  unit_test/test_spdm_responder/algorithms.c
Labels: test

#2583 Update cmocka version in documentation
  README.md
Labels: documentation

#2586 Enhance `libspdm_debug_print` documentation
  include/hal/library/debuglib.h
Labels: documentation, enhancement

#2597 Add GCC to `test_size_of_spdm_*` for aarch64
  unit_test/test_size/test_size_of_spdm_requester/CMakeLists.txt
  unit_test/test_size/test_size_of_spdm_responder/CMakeLists.txt
Labels: bug, build

#2592 Pass spdm context as cookie to secret lib HAL functions
  .github/workflows/build.yml
  include/hal/library/requester/reqasymsignlib.h
  include/hal/library/responder/asymsignlib.h
  include/hal/library/responder/csrlib.h
  include/hal/library/responder/measlib.h
  include/hal/library/responder/setcertlib.h
  include/library/spdm_lib_config.h
  library/spdm_common_lib/libspdm_com_crypto_service.c
  library/spdm_requester_lib/libspdm_req_encap_challenge_auth.c
  library/spdm_requester_lib/libspdm_req_finish.c
  library/spdm_responder_lib/libspdm_rsp_challenge_auth.c
  library/spdm_responder_lib/libspdm_rsp_csr.c
  library/spdm_responder_lib/libspdm_rsp_key_exchange.c
  library/spdm_responder_lib/libspdm_rsp_measurements.c
  library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
  library/spdm_responder_lib/libspdm_rsp_set_certificate.c
  os_stub/spdm_device_secret_lib_null/lib.c
  os_stub/spdm_device_secret_lib_sample/lib.c
  unit_test/fuzzing/test_requester/test_spdm_requester_challenge/challenge.c
  unit_test/fuzzing/test_requester/test_spdm_requester_key_exchange/key_exchange.c
  unit_test/fuzzing/test_responder/test_spdm_responder_finish_rsp/finish_rsp.c
  unit_test/test_spdm_requester/challenge.c
  unit_test/test_spdm_requester/chunk_get.c
  unit_test/test_spdm_requester/error_test/get_measurements_err.c
  unit_test/test_spdm_requester/error_test/key_exchange_err.c
  unit_test/test_spdm_requester/get_certificate.c
  unit_test/test_spdm_requester/get_measurements.c
  unit_test/test_spdm_requester/key_exchange.c
  unit_test/test_spdm_responder/encap_challenge.c
  unit_test/test_spdm_responder/finish.c
  unit_test/test_spdm_responder/key_exchange.c
  unit_test/test_spdm_responder/measurements.c
  unit_test/test_spdm_responder/psk_exchange.c
Labels: enhancement
