Repository DMTF/libspdm, pull requests merged in 2024-03, with the labels that each got.

#2602 Fix "bad" comparison in libspdm_consttime_is_mem_equal
  include/hal/library/memlib.h
  library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c
Labels: bug

#2605 Update copyright year
  LICENSE.md
Labels: documentation

#2611 Use correct message size when logging to transcript
  library/spdm_responder_lib/libspdm_rsp_certificate.c
  library/spdm_responder_lib/libspdm_rsp_digests.c
Labels: bug

#2625 Fix API spelling
  doc/api/common_api.md
  doc/api/requester_api.md
Labels: documentation

#2627 Add new fuzzing test cases for SPDM 1.3.0
  unit_test/fuzzing/test_requester/test_spdm_requester_get_capabilities/get_capabilities.c
  unit_test/fuzzing/test_requester/test_spdm_requester_negotiate_algorithms/negotiate_algorithms.c
  unit_test/fuzzing/test_responder/test_spdm_responder_algorithms/algorithms.c
  unit_test/fuzzing/test_responder/test_spdm_responder_challenge_auth/challenge_auth.c
Labels: test

#2628 Do some customized settings to cover more code logical branch
  unit_test/fuzzing/test_responder/test_spdm_responder_algorithms/algorithms.c
  unit_test/fuzzing/test_responder/test_spdm_responder_capabilities/capabilities.c
  unit_test/fuzzing/test_responder/test_spdm_responder_certificate/certificate.c
  unit_test/fuzzing/test_responder/test_spdm_responder_challenge_auth/challenge_auth.c
  unit_test/fuzzing/test_responder/test_spdm_responder_csr/csr.c
  unit_test/fuzzing/test_responder/test_spdm_responder_digests/digests.c
  unit_test/fuzzing/test_responder/test_spdm_responder_finish_rsp/finish_rsp.c
  unit_test/fuzzing/test_responder/test_spdm_responder_heartbeat_ack/heartbeat_ack.c
  unit_test/fuzzing/test_responder/test_spdm_responder_key_exchange/key_exchange.c
  unit_test/fuzzing/test_responder/test_spdm_responder_key_update/key_update.c
  unit_test/fuzzing/test_responder/test_spdm_responder_measurements/measurements.c
  unit_test/fuzzing/test_responder/test_spdm_responder_psk_exchange_rsp/psk_exchange_rsp.c
  unit_test/fuzzing/test_responder/test_spdm_responder_psk_finish_rsp/psk_finish_rsp.c
  unit_test/fuzzing/test_responder/test_spdm_responder_set_certificate/set_certificate_rsp.c
  unit_test/fuzzing/test_responder/test_spdm_responder_version/version.c
Labels: test

#2622 Fix fuzzy test case libspdm_test_responder_chunk_send_ack_case1
  unit_test/fuzzing/test_responder/test_spdm_responder_chunk_send_ack/chunk_send_ack.c
Labels: test

#2629 CI/CD fuzzer should ignore documentation.
  .github/workflows/cifuzz.yml
Labels: test

#2630 Fix error code for unsupported_req error.
  library/spdm_requester_lib/libspdm_req_encap_certificate.c
  library/spdm_requester_lib/libspdm_req_encap_challenge_auth.c
  library/spdm_requester_lib/libspdm_req_encap_digests.c
  library/spdm_requester_lib/libspdm_req_encap_key_update.c
  library/spdm_responder_lib/libspdm_rsp_chunk_get.c
  library/spdm_responder_lib/libspdm_rsp_chunk_send_ack.c
  library/spdm_responder_lib/libspdm_rsp_csr.c
  library/spdm_responder_lib/libspdm_rsp_encap_response.c
  library/spdm_responder_lib/libspdm_rsp_end_session.c
  library/spdm_responder_lib/libspdm_rsp_finish.c
  library/spdm_responder_lib/libspdm_rsp_heartbeat.c
  library/spdm_responder_lib/libspdm_rsp_key_exchange.c
  library/spdm_responder_lib/libspdm_rsp_key_update.c
  library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
  library/spdm_responder_lib/libspdm_rsp_psk_finish.c
  library/spdm_responder_lib/libspdm_rsp_set_certificate.c
Labels: bug
