Repository DMTF/libspdm, pull requests merged in 2024-07, with the labels that each got.

#2733 Add fuzz testing for MEASUREMENT_EXTENSION_LOG.
  CMakeLists.txt
  unit_test/fuzzing/fuzzing_AFL.sh
  unit_test/fuzzing/fuzzing_AFLTurbo.sh
  unit_test/fuzzing/fuzzing_AFLplusplus.sh
  unit_test/fuzzing/fuzzing_LibFuzzer.sh
  unit_test/fuzzing/oss_fuzz.sh
  unit_test/fuzzing/run_initial_seed.sh
  unit_test/fuzzing/seeds/test_spdm_requester_get_measurement_extension_log/measurement_extension_log.raw
  unit_test/fuzzing/seeds/test_spdm_responder_measurement_extension_log/get_measurement_extension_log.raw
  unit_test/fuzzing/test_requester/test_spdm_requester_get_measurement_extension_log/CMakeLists.txt
  unit_test/fuzzing/test_requester/test_spdm_requester_get_measurement_extension_log/get_measurement_extension_log.c
  unit_test/fuzzing/test_responder/test_spdm_responder_measurement_extension_log/CMakeLists.txt
  unit_test/fuzzing/test_responder/test_spdm_responder_measurement_extension_log/measurement_extension_log.c
Labels: test

#2748 Fix SET_CERTIFICATE issues
  library/spdm_requester_lib/libspdm_req_set_certificate.c
  unit_test/test_spdm_requester/set_certificate.c
Labels: bug

#2747 Remove unused variable
  include/hal/library/debuglib.h
Labels: bug, build

#2751 Fix build break
  unit_test/fuzzing/test_requester/test_spdm_requester_get_measurement_extension_log/get_measurement_extension_log.c
Labels: bug, build

#2753 Update API documentation for MEL
  doc/api/requester_api.md
Labels: documentation

#2752 Check state of buffers at end of test
  unit_test/spdm_unit_test_common/common.c
Labels: enhancement, test

#2754 Update documentation for 3.4 release
  README.md
Labels: documentation

#2715 Add unit tests for MEASUREMENT_EXTENSION_LOG
  unit_test/test_spdm_requester/get_measurement_extension_log.c
  unit_test/test_spdm_requester/test_spdm_requester.c
  unit_test/test_spdm_responder/measurement_extension_log.c
  unit_test/test_spdm_responder/test_spdm_responder.c
Labels: test

#2757 Fix `MEAS_CAP` build failures
  library/spdm_responder_lib/libspdm_rsp_challenge_auth.c
  library/spdm_responder_lib/libspdm_rsp_key_exchange.c
  library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
  os_stub/spdm_device_secret_lib_null/lib.c
  os_stub/spdm_device_secret_lib_sample/lib.c
  unit_test/test_spdm_responder/key_exchange.c
  unit_test/test_spdm_responder/psk_exchange.c
  unit_test/test_spdm_responder/receive_send.c
Labels: bug, build

#2763 Do not zeroize receive buffer
  doc/design.md
  library/spdm_requester_lib/libspdm_req_challenge.c
  library/spdm_requester_lib/libspdm_req_encap_request.c
  library/spdm_requester_lib/libspdm_req_end_session.c
  library/spdm_requester_lib/libspdm_req_finish.c
  library/spdm_requester_lib/libspdm_req_get_capabilities.c
  library/spdm_requester_lib/libspdm_req_get_certificate.c
  library/spdm_requester_lib/libspdm_req_get_csr.c
  library/spdm_requester_lib/libspdm_req_get_digests.c
  library/spdm_requester_lib/libspdm_req_get_event_types.c
  library/spdm_requester_lib/libspdm_req_get_measurement_extension_log.c
  library/spdm_requester_lib/libspdm_req_get_measurements.c
  library/spdm_requester_lib/libspdm_req_get_version.c
  library/spdm_requester_lib/libspdm_req_handle_error_response.c
  library/spdm_requester_lib/libspdm_req_heartbeat.c
  library/spdm_requester_lib/libspdm_req_key_exchange.c
  library/spdm_requester_lib/libspdm_req_key_update.c
  library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c
  library/spdm_requester_lib/libspdm_req_psk_exchange.c
  library/spdm_requester_lib/libspdm_req_psk_finish.c
  library/spdm_requester_lib/libspdm_req_set_certificate.c
  library/spdm_requester_lib/libspdm_req_vendor_request.c
Labels: bug

#2766 Remove unused typedef
  include/internal/libspdm_common_lib.h
Labels: refactor

#2764 Enforce non-zero measurement count
  library/spdm_responder_lib/libspdm_rsp_measurements.c
Labels: enhancement

#2772 Add more libspdm usage.
  README.md
Labels: documentation

#2773 Remove disclaimer from readme
  README.md
Labels: documentation

#2770 Fix the incorrect use of logical negation in the unit tests.
  unit_test/test_spdm_requester/error_test/key_exchange_err.c
  unit_test/test_spdm_requester/key_exchange.c
  unit_test/test_spdm_requester/key_update.c
  unit_test/test_spdm_requester/psk_exchange.c
  unit_test/test_spdm_responder/key_exchange.c
  unit_test/test_spdm_responder/key_update.c
  unit_test/test_spdm_responder/psk_exchange.c
Labels: test

#2775 add unit test : Requester and Responder set HANDSHAKE_IN_THE_CLEAR_CAP to 0.
  unit_test/test_spdm_requester/finish.c
  unit_test/test_spdm_responder/finish.c
Labels: test

#2785 Update specification versions / revisions
  README.md
Labels: documentation

#2788 Squash code coverage commits
  .github/workflows/code_coverage.yml
Labels: enhancement, test
