Repository DMTF/libspdm, pull requests merged in 2024-12, with the labels that each got.

#2918 fix req length calculation for set_key_pair_info.
  library/spdm_requester_lib/libspdm_req_set_key_pair_info.c
Labels: bug

#2922 Fix `SET_CERTIFICATE` build break
  include/library/spdm_lib_config.h
  os_stub/spdm_device_secret_lib_sample/set_cert.c
  unit_test/test_spdm_responder/set_certificate_rsp.c
Labels: bug, build

#2924 Fix spelling errors
  include/hal/base.h
  include/hal/library/cryptlib/cryptlib_cert.h
  include/industry_standard/spdm.h
  include/library/spdm_common_lib.h
  library/spdm_common_lib/libspdm_com_context_data.c
  library/spdm_crypt_lib/libspdm_crypt_cert.c
  library/spdm_requester_lib/libspdm_req_common.c
  library/spdm_requester_lib/libspdm_req_handle_error_response.c
  library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c
  library/spdm_responder_lib/libspdm_rsp_chunk_send_ack.c
  os_stub/cryptlib_mbedtls/pk/x509.c
  os_stub/cryptlib_null/pk/x509.c
  os_stub/cryptlib_openssl/pk/x509.c
  os_stub/spdm_cert_verify_callback_sample/spdm_cert_verify_callback_internal.h
  unit_test/test_spdm_common/context_data.c
  unit_test/test_spdm_requester/get_version.c
Labels: bug, documentation

#2923 Cleanup csrlib
  include/hal/library/responder/csrlib.h
  library/spdm_responder_lib/libspdm_rsp_csr.c
  os_stub/spdm_device_secret_lib_null/lib.c
  os_stub/spdm_device_secret_lib_sample/csr.c
  unit_test/test_spdm_responder/csr.c
Labels: enhancement

#2932 Use Ubuntu 22.04 for uncrustify
  .github/workflows/compliance-checks.yml
Labels: test

#2930 Clean up minor x.509 issues
  os_stub/cryptlib_mbedtls/pk/x509.c
Labels: documentation, refactor

#2939 Add comment explaining MUT_AUTH_CAP check
  library/spdm_requester_lib/libspdm_req_get_capabilities.c
  library/spdm_responder_lib/libspdm_rsp_capabilities.c
Labels: documentation

#2938 Fix opaque data check size calculation issue.
  library/spdm_common_lib/libspdm_com_opaque_data.c
Labels: bug
