Repository DMTF/libspdm, pull requests merged in 2025-03, with the labels that each got.

#2993 Fix old-style-declaration warning
  library/spdm_crypt_lib/libspdm_crypt_cert.c
Labels: refactor

#2994 Fix incorrect error data for UnsupportedRequest
  library/spdm_responder_lib/libspdm_rsp_measurement_extension_log.c
Labels: bug

#2995 Change SET_KEY_PAIR_INFO_ACK error to InvalidRequest
  library/spdm_responder_lib/libspdm_rsp_set_key_pair_info_ack.c
Labels: bug

#3004 Refactor Responder's key exchange code
  library/spdm_responder_lib/libspdm_rsp_finish.c
  library/spdm_responder_lib/libspdm_rsp_key_exchange.c
Labels: refactor

#3010 Fix spelling mistakes across the repository
  doc/api/common_api.md
  doc/api/secured_message_api.md
  doc/fips.md
  doc/test.md
  os_stub/cryptlib_mbedtls/pk/x509.c
  os_stub/cryptlib_null/pk/x509.c
  os_stub/cryptlib_openssl/pk/x509.c
  os_stub/debuglib/debuglib.c
  os_stub/mbedtlslib/include/mbedtls/libspdm_mbedtls_config.h
  os_stub/spdm_device_secret_lib_sample/read_special_cert.c
  unit_test/fuzzing/test_requester/test_spdm_requester_key_update/key_update.c
  unit_test/fuzzing/test_responder/test_spdm_responder_algorithms/algorithms.c
  unit_test/fuzzing/test_responder/test_spdm_responder_chunk_get/chunk_get.c
  unit_test/test_spdm_common/context_data.c
  unit_test/test_spdm_requester/encap_certificate.c
  unit_test/test_spdm_requester/encap_key_update.c
  unit_test/test_spdm_requester/error_test/get_digests_err.c
  unit_test/test_spdm_requester/error_test/get_measurements_err.c
  unit_test/test_spdm_requester/error_test/negotiate_algorithms_err.c
  unit_test/test_spdm_requester/get_certificate.c
  unit_test/test_spdm_requester/get_measurements.c
  unit_test/test_spdm_requester/key_update.c
  unit_test/test_spdm_responder/certificate.c
  unit_test/test_spdm_responder/chunk_get.c
  unit_test/test_spdm_responder/chunk_send_ack.c
  unit_test/test_spdm_responder/csr.c
  unit_test/test_spdm_responder/encap_get_digests.c
  unit_test/test_spdm_responder/key_update.c
  unit_test/test_spdm_responder/measurements.c
  unit_test/test_spdm_responder/set_certificate_rsp.c
Labels: documentation

#3013 Clean up PCIe headers
  include/industry_standard/pci_idekm.h
  include/industry_standard/pci_tdisp.h
  include/industry_standard/pcidoe.h
Labels: documentation

#3020 Add executable permissions to fuzzing_AFLplusplus
  unit_test/fuzzing/fuzzing_AFLplusplus.sh
Labels: test

#3017 Update readme to include TF-RMM.
  README.md
Labels: documentation
