Repository DMTF/libspdm, pull requests merged in 2025-09, with the labels that each got.

#3230 Add C language highlighting to user guide
  doc/user_guide.md
Labels: documentation

#3227 1.4 Fix incorrect message offset caused by send_ack_response size change
  library/spdm_responder_lib/libspdm_rsp_receive_send.c
Labels: bug

#3238 Use `LIBSPDM_SEND_CHALLENGE_SUPPORT`
  include/library/spdm_requester_lib.h
  library/spdm_requester_lib/libspdm_req_challenge.c
  unit_test/fuzzing/test_requester/test_spdm_requester_challenge/challenge.c
  unit_test/test_spdm_requester/challenge.c
Labels: bug

#3225 Initial draft for unit test template
  doc/internal/unit_test_template.md
Labels: documentation, test

#3248 Reapply "Remove unused parameter"
  include/internal/libspdm_common_lib.h
  library/spdm_common_lib/libspdm_com_crypto_service_session.c
  library/spdm_requester_lib/libspdm_req_key_exchange.c
  library/spdm_requester_lib/libspdm_req_psk_exchange.c
  library/spdm_responder_lib/libspdm_rsp_key_exchange.c
  library/spdm_responder_lib/libspdm_rsp_psk_exchange.c
Labels: refactor

#3247 Move event handlers to common library
  include/internal/libspdm_common_lib.h
  library/spdm_common_lib/CMakeLists.txt
  library/spdm_common_lib/libspdm_com_event.c
  library/spdm_requester_lib/libspdm_req_encap_event_ack.c
Labels: refactor
