Repository DMTF/libspdm, pull requests merged in 2025-02, with the labels that each got.

#2965 Add algorithm masks and helper functions
  include/industry_standard/spdm.h
  include/internal/libspdm_common_lib.h
  library/spdm_common_lib/libspdm_com_support.c
Labels: enhancement

#2971 CMakeLists.txt: Support x86_64 ARCH
  CMakeLists.txt
Labels: build

#2973 Add EP_INFO_CAP check
  library/spdm_requester_lib/libspdm_req_get_capabilities.c
  library/spdm_responder_lib/libspdm_rsp_capabilities.c
Labels: bug

#2960 Fix `ENCAP_CAP` checks to accommodate SPDM 1.2
  library/spdm_requester_lib/libspdm_req_key_exchange.c
  library/spdm_responder_lib/libspdm_rsp_encap_response.c
Labels: bug

#2981 Update QEMU link to upstream repository
  README.md
Labels: documentation

#2986 Return proper error code when session is required
  library/spdm_requester_lib/libspdm_req_encap_key_update.c
Labels: bug
