Repository DMTF/libspdm, pull requests merged in 2025-05, with the labels that each got.

#3056 uncrustify: Upgrade the config to 0.78
  .github/workflows/compliance-checks.yml
  .uncrustify.cfg
  os_stub/cryptlib_openssl/pk/x509.c
  script/format_nix.sh
  unit_test/test_size/malloclib_simple/malloclib.c
  unit_test/test_spdm_requester/get_capabilities.c
  unit_test/test_spdm_responder/challenge_auth.c
  unit_test/test_spdm_responder/encap_response.c
  unit_test/test_spdm_responder/respond_if_ready.c
Labels: refactor

#3066 Add unit test for `ProvisionedSlotMask` and `SupportedSlotMask`
  library/spdm_requester_lib/libspdm_req_get_digests.c
  unit_test/test_spdm_requester/error_test/get_digests_err.c
Labels: documentation, test

#3078 Fix grammar in user guide
  doc/user_guide.md
Labels: documentation
