Repository DMTF/libspdm, pull requests merged in 2025-01, with the labels that each got.

#2946 Update copyright year to 2025
  LICENSE.md
Labels: documentation

#2963 Fix libspdm_hmac_new return type
  library/spdm_crypt_lib/libspdm_crypt_hmac.c
Labels: bug

#2964 Add wolfSSL to readme.
  README.md
Labels: documentation

#2966 Update upload-artifact version
  .github/workflows/cifuzz.yml
Labels: bug, test, build

#2967 Update README to latest SPDM specifications
  README.md
Labels: documentation

#2969 Change PCIE to PCIe
  README.md
  include/industry_standard/cxl_idekm.h
  include/library/spdm_transport_pcidoe_lib.h
  library/spdm_transport_pcidoe_lib/libspdm_doe_pcidoe.c
Labels: documentation
